name: "Hjem impure tests"
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: ['**.nix']
  pull_request:
    branches: [ "master" ]
    paths: ['**.nix']
jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters = https://cache.nixos.org/ https://feel-co.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= feel-co.cachix.org-1:nwEFNnwZvtl4KKSH5LDg+/+K7bV0vcs6faMHAJ6xx0w=

    - run: nix flake check -L
