name: "Hjem impure tests"
on:
  push:
    branches: [ "master" ]
    paths: ['**.nix']
  pull_request:
    branches: [ "master" ]
    paths: ['**.nix']
jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix flake check -L
